[package]
name = "ckb-safe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.12.1"
secp256k1-sys = "0.1.1"
